# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2025'
tagline:          'A workshop for GAP developers and users'
description:      '7-11 April 2025'
location:         'Vrije Universiteit Brussel'
url:              https://www.gapdays.de
baseurl:          /gapdays2025-spring
email:            gapdays2025-spring@gapdays.de

exclude: 
    - "LICENSE.hyde.md"
    - "README.hyde.md"
    - "TODO.md"
    - "program.aux"
    - "program.log"
    - "program.out"
    - "program.tex"
    - "misc"
